homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: pages/default/index.html.twig
        _locale: '%locale%'

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications